### ISSUE TITLE
Tell people to change COC file name

### ISSUE THREAD

**Issue by sckott** [ropensci/software-review-meta#46] opened 2018-04-11 05:21 UTC
only if it's `CONDUCT.md`, then change to `CODE_OF_CONDUCT.md` - i do realize `usethis` already has the latter, so all people using that will be fine

**Comment by maelle** [comment] 2018-06-20 11:16
This should be a wave of PRs. 🤔

**Comment by maelle** [comment] 2018-11-26 13:41
Maybe a tech note would help to increase awareness. 🤔

**Comment by sckott** [comment] 2018-11-26 14:54
good idea

**Comment by maelle** [comment] 2018-11-26 14:55
Or would it make sense to couple that with a blog post about the updates you and Stef made to the rOpenSci COC? 🤔

**Comment by stefaniebutland** [comment] 2018-11-26 16:56
Code of conduct updates not finished yet but will be live in Dec. I guess we do need to put out a *short* post announcing that we've made updates, to name Committee etc, so could note this issue there

**Comment by maelle** [comment] 2021-01-12 15:58
Duplicate of https://github.com/ropensci/dev_guide/issues/240

**Closed by maelle** 2021-01-12 15:58 UTC
Labels: standards
